[plugins]
arduino-cli = "https://github.com/egnor/asdf-arduino-cli.git"

[tools]
python = {version = "3.11", virtualenv = "build/python_venv"}
arduino-cli = {version = "0.35.3"}

[settings]
experimental = true
python_compile = false
python_venv_auto_create = true

[env]
ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS = "https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json"
ARDUINO_DIRECTORIES_DATA = "{{config_root}}/build/arduino"
ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL = "true"
