[plugins]
arduino-cli = "https://github.com/egnor/asdf-arduino-cli.git"

[tools]
python = {version = "3.11", virtualenv = "build/python_venv"}
arduino-cli = {version = "0.35.3"}

[settings]
experimental = true
python_venv_auto_create = true

[env]
ARDUINO_DIRECTORIES_DATA = "{{config_root}}/build/arduino"
ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL = "true"
