# Python project metadata, including dependencies & tool settings
# https://snarky.ca/what-the-heck-is-pyproject-toml

[project]
name = "blub"
version = "0.1"
requires-python = ">=3.12"

# Dependencies needed at runtime
dependencies = [
  "exif~=1.6.1",
  "ok-logging-setup~=0.17",
  "ok-serial~=0.8",
  "ok-subprocess-runner~=0.5",
  "ok-serial-terminal~=0.4",
  "pint~=0.24",
  "python-debian>=1.0.1",
  "tomli-w>=1.2.0",
  "pytest>=9.1.1",
  "pytest-asyncio>=1.4.0",
  "aiomqtt>=3.0.0a1",
]

[tool.pytest]
addopts = ["--import-mode=importlib"]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.ruff]
line-length = 80
