# MCUboot config for the nRF9151 Feather
# (adapted from circuitdojo/ncs-serial-modem app/sysbuild/mcuboot/boards/)

# Avoid generating serial chatter
CONFIG_CONSOLE=n
# Do not mess with the nPM1300
CONFIG_GPIO_NPM13XX=n
CONFIG_MFD_NPM13XX=n
