# Send logs to the debug port. (See them with `mise run cell-modem-logs`)
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_BACKEND_RTT=y
# Drop, don't block, with no listener.
CONFIG_LOG_BACKEND_RTT_MODE_DROP=y

CONFIG_SM_CUSTOMER_VERSION="blub"

# No flow control, allow generous buffer
CONFIG_SM_UART_RX_BUF_SIZE=2048
# Unsolicited Result Code (eg. MQTT inbound)
CONFIG_SM_URC_BUFFER_SIZE=8192
# Command "data mode" (eg. MQTT outbound)
CONFIG_SM_DATAMODE_BUF_SIZE=8192

# Disable things we don't use
CONFIG_SM_SMS=n
CONFIG_SM_NRF_CLOUD=n
CONFIG_SM_COAPC=n
CONFIG_SM_HTTPC=n
