name=blub cell_modem
version=0.0
author=egnor
maintainer=egnor
sentence=blub cell modem interface
paragraph=
url=https://github.com/egnor/blub
depends=blub config, Embedded Template Library ETL
dot_a_linkage=true
